damndaily/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^damndaily/', include('webapp.urls', namespace='webapp')),
    url(r'^admin/', admin.site.urls),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views, account, auth

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^save/$', views.save_damn_daily, name='save_damn_daily'),

    url(r'^daily/(?P<damndailyid>[a-zA-Z0-9]+)/$', views.view, name='view'),
    url(r'^daily/(?P<damndailyid>[a-zA-Z0-9]+)/subscribe/$',
        views.subscribe, name='subscribe'),
    url(r'^daily/(?P<damndailyid>[a-zA-Z0-9]+)/save_subscription/$',
        views.save_subscription, name='save_subscription'),
    url(r'daily/(?P<damndailyid>[a-zA-Z0-9]+)/unsubscribe/$',
        views.unsubscribe, name='unsubscribe'),

    url(r'^today/(?P<todayid>[a-zA-Z0-9]+)/$',
        views.TodayDetailView.as_view(), name='today'),
    url(r'^today/(?P<todayid>[a-zA-Z0-9]+)/update_today/$',
        views.update_today, name='update_today'),

    url(r'^today/(?P<todayid>[a-zA-Z0-9]+)/participate/$',
        views.participate, name='participate'),
    url(r'^today/(?P<todayid>[a-zA-Z0-9]+)/reject/$',
        views.reject, name='reject'),

    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^reset_password/$', auth.reset_password, name='reset_password'),
    url(r'^register/$', auth.register, name='register'),
    url(r'^accounts/profile/$', account.profile, name='profile'),
    url('^', include('django.contrib.auth.urls')),
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date


class DamnDaily(models.Model):
    name = models.CharField(max_length=512)
    created = models.DateTimeField(default=timezone.now)
    deleted = models.DateTimeField(null=True, blank=True)
    external_id = models.CharField(max_length=24)
    admin_key = models.CharField(max_length=8)

    def __str__(self):
        return '<DamnDaily name={:s}>'.format(self.name)


class Subscription(models.Model):
    start = models.DateTimeField(default=timezone.now)
    end = models.DateTimeField(null=True, blank=True)
    damndaily = models.ForeignKey('DamnDaily', on_delete=models.CASCADE)
    user = models.ForeignKey(User)

    def __str__(self):
        fmt = '<Subscription daily={0:s}  user={1:s} active={2:b}'
        fmt_obj = [self.damndaily.name, self.user.username, not self.end]
        fmt = ''.join([fmt, '>'])
        return fmt.format(*fmt_obj)


class Today(models.Model):
    day = models.DateField(null=True, default=date.today)
    time = models.TimeField(null=True, blank=True)
    location = models.CharField(max_length=512)
    damndaily = models.ForeignKey('DamnDaily', on_delete=models.CASCADE)

    def __str__(self):
        fmt = '<Today daily={0:s}  day={1:%d.%m.%Y}'
        fmt_obj = [self.damndaily.name, self.day]
        if self.time:
            fmt = ''.join([fmt, ' time={2:%H:%M}'])
            fmt_obj.append(self.time)
        fmt = ''.join([fmt, '>'])
        return fmt.format(*fmt_obj)


class Participation(models.Model):
    today = models.ForeignKey('Today', on_delete=models.CASCADE)
    user = models.ForeignKey(User)

    def __str__(self):
        return '<Participation today={:s}' \
            ' user={:s}>'.format(str(self.today), str(self.user))


class Message(models.Model):
    value = models.TextField()
    send = models.DateTimeField(auto_now_add=True)
    today = models.OneToOneField('Today',
                                 on_delete=models.CASCADE,
                                 primary_key=True)
    author = models.OneToOneField(User)


class GeneratedUsername(models.Model):
    """See https://github.com/mattconsto/fantasy-names for generation
    """
    username = models.CharField(max_length=128, unique=True)
    group = models.CharField(max_length=64)
    individual = models.CharField(max_length=64)
    gender = models.SmallIntegerField()

    def __str__(self):
        fmt = '<GeneratedUsername username={0.username}' \
            ' group={0.group}' \
            ' individual={0.individual}' \
            ' gender={0.gender}'
        return fmt.format(self)

webapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
from datetime import date
from .models import DamnDaily, Today, Participation, Message
from . import services


class TodayDetailView(generic.DetailView):
    model = Today


def index(request):
    return render(request, 'webapp/welcome.html')


@login_required
def create(request):
    return render(request, 'webapp/damndaily/create.html')


@login_required
def subscribe(request, damndailyid):
    return render(request, 'webapp/damndaily/subscribe.html')


@login_required
def unsubscribe(request, damndailyid):
    pass


def save_subscription(request, damndailyid, username):
    return HttpResponse('subscribe damn daily id: %s' % (damndailyid,))


def save_damn_daily(request):
    daily = DamnDaily(name=request.POST['name'],
                      external_id=services.create_damndaily_id(),
                      admin_key=services.random_string(8))
    daily.save()
    return HttpResponseRedirect(reverse('webapp:view',
                                        args=(daily.external_id,)))


def view(request, damndailyid):
    damndaily = get_object_or_404(DamnDaily, external_id=damndailyid)

    participations = Participation.objects \
        .filter(today__day=date.today()) \
        .filter(today__damndaily__external_id=damndailyid)

    try:
        today = Today.objects \
            .filter(damndaily__external_id=damndailyid) \
            .get(day=date.today())
    except Today.DoesNotExist:
        today = Today(day=date.today(), damndaily=damndaily)
        today.save()

    messages = Message.objects.filter(today=today)

    context = {
        'participations': participations,
        'damndaily': damndaily,
        'today': today,
        'messages': messages
    }
    return render(request, 'webapp/damndaily/index.html', context)


def update_today(request, todayid):
    today = get_object_or_404(Today, pk=todayid)
    today.time = request.POST['time']
    today.location = request.POST['location']
    today.save()
    return HttpResponseRedirect(reverse('webapp:view',
                                        args=(today.damndaily.external_id,)))


def participate(request, todayid):
    today = get_object_or_404(Today, pk=todayid)
    participation = Participation(today=today, user=request.user)
    participation.save()
    return HttpResponseRedirect(reverse('webapp:view',
                                        args=(today.damndaily.external_id,)))


def reject(request, todayid):
    pass

webapp/templates/webapp/damndaily/create.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
<section>
    <header>
        <h3>{% trans 'New Damn daily' %}</h3>
    </header>
    <form action="{% url 'webapp:save_damn_daily' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="name">{% trans 'Name' %}</label>
            <input type="text" name="name" required="required">
        </div>
        <div>
            <input type="submit" value="{% trans 'Save' %}">
        </div>
    </form>
</section>


{% endblock content %}

webapp/templates/webapp/damndaily/index.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
<section>
    <header>
        <h3>{{ damndaily.name }}</h3>
        {% if today %}
        <h4>{{ today.day}}
        {% if today.time %}
            {{ today.time }}
        {% endif %}</h4>
        {% endif %}
        <h4>Teilnehmer</h4>
    </header>
    <ul>
        {% for participation in participations %}
        <li>{{ participation.user }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'webapp:subscribe' damndaily.external_id %}">{% trans 'Contribute this link to your folks' %}</a>
</section>
<section>
    <form action="{% url 'webapp:update_today' today.id %}" method="post">
        {% csrf_token %}
        <div>
            <label for="day">{% trans 'Day' %}</label>
            <input type="text" readonly="readonly" value="{{ today.day }}">
        </div>
        <div>
            <label for="day">{% trans 'At' %}</label>
            <input type="time" value="{{ today.time }}" name="time">
        </div>
        <div>
            <label for="location">{% trans 'Where' %}</label>
            <input type="text" value="{{ today.location }}" name="location" maxlength="512">
        </div>
        <div>
            <input type="submit" value="{% trans 'Save' %}">
        </div>
    </form>
</section>

<section>
    <a href="{% url "webapp:participate" today.id %}">{% trans 'Participate' %}</a>
    <a href="{% url "webapp:reject" today.id %}">{% trans 'Reject' %}</a>
    <a href="{% url "webapp:unsubscribe" damndaily.id %}">{% trans 'Unsubscribe' %}</a>
</section>

{% if messages %}
<section>
    <ul>
        {% for msg in messages %}
            <li>
                <div>
                    <aside>{{ msg.author }}</aside>
                    <p>{{ msg.value }}</p>
                    <aside>{{ msg.send }}</aside>
                </div>
            </li>
        {% endfor %}
    </ul>
</section>
{% endif %}

{% endblock content %}

webapp/templates/webapp/damndaily/subscribe.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
<section>
    <header>
        <h3>{% trans 'Subscribe' %}</h3>
    </header>
    <form action="{% url 'webapp:save_subscription' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="damndaily">Damn daily</label>
            <input type="text" name="damndailyid" disabled="disabled" value="{{ damndailyid }}">
        </div>
        <div>
            <label for="name">Name</label>
            <input type="text" name="username" required="required" value="{{ generated_username }}">
        </div>
        <div>
            <input type="submit" value="{% trans 'Save' %}">
        </div>
    </form>
</section>


{% endblock content %}

webapp/templates/webapp/index.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
<section>
    <header>
        <h3>{{ damndaily.name }}</h3>
        {% if today %}
        <h4>{{ today.day}}
        {% if today.time %}
            {{ today.time }}
        {% endif %}</h4>
        {% endif %}
        <h4>Teilnehmer</h4>
    </header>
    <ul>
        {% for participation in participations %}
        <li>{{ participation.user }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'webapp:partake' damndaily.external_id %}">{% trans 'Contribute this link to your folks' %}</a>
</section>
<section>
    <form action="{% url 'webapp:update_today' today.id %}" method="post">
        {% csrf_token %}
        <div>
            <label for="day">{% trans 'Day' %}</label>
            <input type="text" readonly="readonly" value="{{ today.day }}">
        </div>
        <div>
            <label for="day">{% trans 'At' %}</label>
            <input type="time" value="{{ today.time }}" name="time">
        </div>
        <div>
            <label for="location">{% trans 'Where' %}</label>
            <input type="text" value="{{ today.location }}" name="location" maxlength="512">
        </div>
        <div>
            <input type="submit" value="{% trans 'Save' %}">
        </div>
    </form>
</section>

{% if messages %}
<section>
    <ul>
        {% for msg in messages %}
            <li>
                <div>
                    <aside>{{ msg.author }}</aside>
                    <p>{{ msg.value }}</p>
                    <aside>{{ msg.send }}</aside>
                </div>
            </li>
        {% endfor %}
    </ul>
</section>
{% endif %}

{% endblock content %}

webapp/templates/webapp/layout.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block pagetitle %}{% endblock pagetitle %}</title>
</head>

<body>
    <div class="content">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/webapp/partake.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
<section>
    <header>
        <h3>{% trans 'Partake' %}</h3>
    </header>
    <form action="{% url 'webapp:save_partake' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="damndaily">Damn daily</label>
            <input type="text" name="damndailyid" disabled="disabled" value="{{ damndailyid }}">
        </div>
        <div>
            <label for="name">Name</label>
            <input type="text" name="username" required="required" value="{{ generated_username }}">
        </div>
        <div>
            <input type="submit" value="{% trans 'Save' %}">
        </div>
    </form>
</section>


{% endblock content %}

webapp/templates/webapp/welcome.html
{% extends "webapp/layout.html" %}
{% load i18n %}

{% block content %}
Hallo Welt

<a href="{% url "webapp:create" %}">Erstelle ein neues verdammtes Tägliches</a>
{% endblock content %}